config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  resources :jobs, only: [:index, :show] do
    member do
      get 'apply'
      post 'submit_application'
      get 'confirm'
    end
  end
  
devise_for :users, controllers: {
  passwords: 'passwords'
} 
  resources :inquiries, only: [:create]

  namespace :admin do
    root 'dashboard#index'
    resource :page_contents, only: [:edit, :update]
    resource :contacts, only: [:edit, :update]
    resources :inquiries, only: [:index]
    resources :users, only: [:index, :new, :create, :destroy]
    resources :skills
    resources :categories
    resources :jobs do
      resources :applications, only: [] do
        member do
          patch 'shortlist', to: 'applications#shortlist', as: :shortlist
          patch 'reject', to: 'applications#reject', as: :reject
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @active_jobs = Job.active.count
    @inactive_jobs = Job.where(status: 'false').count
    @under_review_applications = Application.where(status: :under_review).count
    @shortlisted_applications = Application.where(status: :shortlisted).count
    @rejected_applications = Application.where(status: :rejected).count
    @inquiries = Inquiry.count
    @latest_closing_jobs = Job.where(status: true).order(closing_date: :asc).limit(3).load_async
    @latest_inquiries = Inquiry.order(created_at: :desc).limit(3).load_async
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
 <div class="d-flex">
    <div class="main-content col">
        <div class="d-flex justify-content-between mt-4">
            <div class="card card-dashboard bg col-3">
                <h4 class="display-2 txt fw-bold"><%= @active_jobs + @inactive_jobs %></h4>
                <p>Active - <%= @active_jobs %><br>Inactive - <%= @inactive_jobs %><br> Total Jobs</p>
            </div>
            <div class="card card-dashboard bg col-3">
            <h4 class="display-2 fw-bold txt"><%= @under_review_applications + @shortlisted_applications + @rejected_applications %></h4>
                    <p>UnderReview - <%= @under_review_applications %><br>Shortlisted - <%= @shortlisted_applications %><br>Total Applications</p>
            </div>
            <div class="card card-dashboard bg col-3">
                <h4 class="display-2 txt fw-bold"><%= @inquiries %></h4>
                <p>Total Inquiries</p>
            </div>
        </div>
        <div class="section-title d-flex justify-content-between align-items-center">
            <span>Closing jobs</span>
            <a href="<%= admin_jobs_path %>" class="arrow-link pb-2">
                <i class="bi bi-arrow-right custom-button"></i>
            </a>
        </div>
        <div class="d-flex ">
            <% @latest_closing_jobs.each do |job| %>
                <div class="job-card me-3 col-4">
                <h5><%= job.title %></h5>
                <p><%= job.location %></p>
                <p><%= truncate(job.description, length: 250) %></p>
                <a href="<%= admin_job_path(job) %>" class="text-white">View Job</a>
                </div>
            <% end %>
        </div>
        <div class="section-title d-flex justify-content-between align-items-center">
            <span>Latest Inquiries</span>
            <a href="<%= admin_inquiries_path %>" class="arrow-link pb-2">
                <i class="bi bi-arrow-right custom-button"></i>
            </a>
        </div>
        <div class="d-flex">
            <% @latest_inquiries.each do |inquiry| %>
                <div class="inquiry-card me-3 col-4">
                    <h5><%= inquiry.name %></h5>
                    <p> <%= truncate(inquiry.message, length: 150) %></p>
                </div>
            <% end %>
        </div>
    </div>
</div>