config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  resources :jobs, only: [:index, :show] do
    member do
      get 'apply'
      post 'submit_application'
      get 'confirm'
    end
  end
  
devise_for :users, controllers: {
  passwords: 'passwords'
} 
  resources :inquiries, only: [:create]

  namespace :admin do
    root 'dashboard#index'
    resource :page_contents, only: [:edit, :update]
    resource :contacts, only: [:edit, :update]
    resources :inquiries, only: [:index]
    resources :users, only: [:index, :new, :create, :destroy]
    resources :skills
    resources :categories
    resources :jobs do
      resources :applications, only: [] do
        member do
          patch 'shortlist', to: 'applications#shortlist', as: :shortlist
          patch 'reject', to: 'applications#reject', as: :reject
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/common/_dashboard.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 " style="width: 280px;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <span class="fs-4">XYZ IT Solutions</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to 'Dashboard', admin_root_path, class: "nav-link text-white #{'active' if current_page?(admin_root_path)}" %>

    </li>
    <%if user_signed_in? && current_user.admin? %>
    <li class="nav-item">
      <%= link_to 'User Management', admin_users_path, class: "nav-link text-white #{'active' if current_page?(admin_users_path)}" %>
    </li>
    <%# <li class="nav-item">
      <%= link_to 'Add User', new_admin_user_path, class: "nav-link text-white #{'active' if current_page?(new_admin_user_path)}" %>
    <%# </li> %> 
    <li class="nav-item">
      <%= link_to 'Manange Contact',edit_admin_contacts_path , class: "nav-link text-white #{'active' if current_page?(edit_admin_contacts_path )}" %>
    </li>
     <li class="nav-item">
      <%= link_to 'Content Management',edit_admin_page_contents_path , class: "nav-link text-white #{'active' if current_page?(edit_admin_page_contents_path )}" %>
    </li>
    <%end%>
    <li class="nav-item">
      <%= link_to 'Jobs', admin_jobs_path, class: "nav-link text-white #{'active' if current_page?(admin_jobs_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Add Job', new_admin_job_path, class: "nav-link text-white #{'active' if current_page?(new_admin_job_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Skills', admin_skills_path, class: "nav-link text-white #{'active' if current_page?(admin_skills_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Categories', admin_categories_path, class: "nav-link text-white #{'active' if current_page?(admin_categories_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Inquiries', admin_inquiries_path, class: "nav-link text-white #{'active' if current_page?(admin_inquiries_path)}" %>
    </li>
  </ul>
</div>
<div class="sidebar-footer mt-auto p-3 ">
  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-danger" %>
</div>
 

app/views/common/_error_messages.html.erb
<% if errors.any? %>
  <div class="text-danger">
    <% errors.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

app/views/common/_footer.html.erb
<footer class="bg text-white py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h5>XYZ IT Solutions</h5>
      </div>
      <div class="col-md-4">
        <ul class="navbar-nav mx-auto d-flex flex-row ">
          <li class="nav-item me-5">
            <%= link_to 'Home', root_path, class: 'nav-link text-white' %>
          </li>
          <li class="nav-item me-5">
            <%= link_to 'About', about_path, class: 'nav-link text-white' %>
          </li>
          <li class="nav-item me-5">
            <%= link_to 'Contact', contact_path, class: 'nav-link text-white' %>
          </li>
          <li class="nav-item me-5">
            <%= link_to 'Career', jobs_path, class: 'nav-link text-white' %>
          </li>
        </ul>
       
      </div>
      <div class="col-md-4 text-md-end">
        <p><strong>Address:</strong> <%= @contact.address %></p>
        <p><strong>Phone:</strong> <%= @contact.phone %></p>
        <p><strong>Email:</strong> <%= @contact.email %></p>
        <p><strong>Website:</strong> <%= @contact.website %></p>
      </div>
    </div>
    <div class="row">
      <div class="col text-center txt">
        <p class="mb-0">&copy; <%= Time.now.year %> XYZ IT Solutions. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/common/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark-blue bg ">
  <a class="navbar-brand txt ps-3" href="<%= root_path %>">MyApp</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Career', jobs_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>